### ISSUE TITLE
mappedAttributes & handleEvent

### ISSUE THREAD

**Issue by thipages** [WebReflection/heresy#18] opened 2019-11-16 10:25 UTC
Hi,
I need to render Test where attributes are used for calculation before rendering.
Since, both attributes a and b are needed to calculate a render, I thought I could catch any changes with handleEvent.

I have observed that ona and onb need to be present to trigger handleEvent.

```javascript
const algorithm=(a,b)=>[a*1.5,b];
export const Test = {
    extends: 'div',
    mappedAttributes:['a','b'],
    // if absent handleEvent will not be called
         ona() {},
         onb() {},
    //
    handleEvent(e) {
        this.render();
    },
    render(){
        const r= algorithm(this.a,this.b);
        this.html `Test : ${r[0]}   -   ${r[1]}`
    }
};
```

**Comment by WebReflection** [comment] 2019-11-16 11:00
That's by design. If you don't have listeners, there's no reason to dispatch, specially because the default handleEvent would automatically trigger `this['on' + event.type](event)`, and it would break if you don't have `on + event.type` in your prototype.

But here the thing: heresy is based on lighterhtml, and the cheapest thing to do in lighterhtml is actually the render, so that you should never care if it's called more than once.

On the other side, you have the guarantee that either `a` or `b` can be changed a part, either via the HTML view, or directly through the element instance.

As summary, this is just fine, and also suggested:
```js
const algorithm=(a,b)=>[a*1.5,b];
export const Test = {
    extends: 'div',
    mappedAttributes:['a', 'b'],
    ona() { this.render(); },
    onb() { this.render(); },
    render(){
        const r= algorithm(this.a, this.b);
        this.html `Test : ${r[0]}   -   ${r[1]}`
    }
};
```
However, if you'd like to simplify this use case per each element that has mapped attributes, you can simply create a tiny utility tht does that for you.

```js
const withMappedAttributes = (attr, def) => Object.assign({}, def, attr.reduce(
  (acc, key) => { acc['on' + key] = def.render; return acc; },
  {mappedAttributes: attr.concat(def.mappedAttributes || [])})
);

export const Test =withMappedAttributes(['a', 'b'], {
    extends: 'div',
    render(){
        const r= algorithm(this.a,this.b);
        this.html `Test : ${r[0]}   -   ${r[1]}`
    }
});
```

In this way, you can solve the same problem for a variety of components, keeping their definition super compact.

I am going to close this, as there's no bug to fix from my side, but feel free to ask me more, if needed.

**Closed by WebReflection** 2019-11-16 11:00 UTC

**Comment by thipages** [comment] 2019-11-16 11:35
Thanks
Such utility or derived will be used!
